banknotes:
  500: 0
  200: 10
  100: 8
  50: 8
  20: 17
  10: 0
  5: 6
  2: 9
  1: 10
accounts:
  3321:
    name: 'Volodymyr'
    password: 'mypass'
    balance: 400
  5922:
    name: 'Iryna'
    password: 'ho#ll_ยง1'
    balance: 5301
