banknotes:
  500: 0
  200: 9
  100: 7
  50: 7
  20: 16
  10: 0
  5: 3
  2: 7
  1: 9
accounts:
  3321:
    name: 'Volodymyr'
    password: 'mypass'
    balance: 289
  5922:
    name: 'Iryna'
    password: 'ho#ll_ยง1'
    balance: 5301
